server:
  port: 8079

spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/scheme.sql #，每次启动程序，程序都会运行schema.sql文件，对数据库的数据操作
    url: jdbc:h2:file:./data/course_database #配置h2数据库的连接地址
    username: course
    password: course_123
    sql-script-encoding: utf-8
    continue-on-error: true
    initialization-mode: embedded
  h2:
    console:
      settings:
        web-allow-others: false
        trace: false
      path: /h2-console
      enabled: true #开启web console功能

